## Logistic regression to predict absenteeism

In [1]:
# import the relevant libraries
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

In [11]:
# checking if dataset is balanced (what % of targets are 1s)
targets.sum() / targets.shape[0]

0.45571428571428574

In [12]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [14]:
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

### Selecting inputs for regression

In [15]:
data_with_targets.shape

(700, 12)

In [16]:
# Selecting all rows and all columns until 14 (excluding) 
data_with_targets.iloc[:,:14]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
5,0,0,0,1,10,179,38,31,0,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4,1
7,0,0,0,1,7,260,36,23,0,4,0,1
8,0,0,1,0,6,155,34,25,0,2,0,1
9,0,0,0,1,7,235,37,29,1,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0,1
11,1,0,0,0,7,260,36,23,0,4,0,1
12,1,0,0,0,7,260,36,23,0,4,0,1
13,1,0,0,0,7,179,38,31,0,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0,1
15,1,0,0,0,7,246,41,23,0,0,0,1
16,0,0,0,1,7,179,38,31,0,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0,1
18,1,0,0,0,7,189,33,25,0,2,2,1
19,0,0,0,1,5,248,47,32,0,2,1,0
20,1,0,0,0,12,330,28,25,1,0,0,1
21,1,0,0,0,3,179,38,31,0,0,0,0
22,1,0,0,0,10,361,28,27,0,1,4,1
23,0,0,0,1,8,260,36,23,0,4,0,1
24,0,0,1,0,8,289,33,30,0,2,1,1
25,0,0,0,1,8,361,28,27,0,1,4,1
26,0,0,0,1,4,289,33,30,0,2,1,0
27,0,0,0,1,12,157,29,22,0,0,0,1
28,0,0,1,0,8,289,33,30,0,2,1,1
29,0,0,0,1,8,179,38,31,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0,1
671,0,0,1,0,4,225,28,24,0,1,2,1
672,1,0,0,0,4,118,50,31,0,1,0,0
673,0,0,0,1,4,179,30,19,1,0,0,0
674,0,0,0,1,7,235,37,29,1,1,1,1
675,0,0,1,0,9,225,41,28,1,2,2,0
676,0,0,0,1,9,235,32,25,1,0,0,0
677,1,0,0,0,9,118,37,28,0,0,0,0
678,0,0,0,1,9,235,43,38,0,1,0,1
679,1,0,0,0,10,179,30,19,1,0,0,0
680,0,0,0,1,10,291,40,25,0,1,1,0
681,1,0,0,0,10,225,41,28,1,2,2,1
682,0,0,1,0,11,300,43,25,0,2,1,1
683,0,0,0,1,11,225,41,28,1,2,2,1
684,0,0,0,1,11,179,30,19,1,0,0,0
685,0,0,0,1,5,118,50,31,0,1,0,0
686,1,0,0,0,5,118,50,31,0,1,0,0
687,0,0,0,1,5,118,37,28,0,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0,0
689,0,0,0,1,5,179,30,19,1,0,0,0
690,0,0,0,0,5,378,36,21,0,2,4,0
691,0,1,0,0,5,179,40,22,1,2,0,0
692,1,0,0,0,5,155,34,25,0,2,0,1
693,1,0,0,0,5,235,32,25,1,0,0,1
694,0,0,0,1,5,291,40,25,0,1,1,1
695,1,0,0,0,5,179,40,22,1,2,0,1
696,1,0,0,0,5,225,28,24,0,1,2,0
697,1,0,0,0,5,330,28,25,1,0,0,1
698,0,0,0,1,5,235,32,25,1,0,0,0
699,0,0,0,1,5,291,40,25,0,1,1,0

In [17]:
# Selecting all rows and all columns but the last one
data_with_targets.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
5,0,0,0,1,10,179,38,31,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4
7,0,0,0,1,7,260,36,23,0,4,0
8,0,0,1,0,6,155,34,25,0,2,0
9,0,0,0,1,7,235,37,29,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0
11,1,0,0,0,7,260,36,23,0,4,0
12,1,0,0,0,7,260,36,23,0,4,0
13,1,0,0,0,7,179,38,31,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0
15,1,0,0,0,7,246,41,23,0,0,0
16,0,0,0,1,7,179,38,31,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0
18,1,0,0,0,7,189,33,25,0,2,2
19,0,0,0,1,5,248,47,32,0,2,1
20,1,0,0,0,12,330,28,25,1,0,0
21,1,0,0,0,3,179,38,31,0,0,0
22,1,0,0,0,10,361,28,27,0,1,4
23,0,0,0,1,8,260,36,23,0,4,0
24,0,0,1,0,8,289,33,30,0,2,1
25,0,0,0,1,8,361,28,27,0,1,4
26,0,0,0,1,4,289,33,30,0,2,1
27,0,0,0,1,12,157,29,22,0,0,0
28,0,0,1,0,8,289,33,30,0,2,1
29,0,0,0,1,8,179,38,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0
671,0,0,1,0,4,225,28,24,0,1,2
672,1,0,0,0,4,118,50,31,0,1,0
673,0,0,0,1,4,179,30,19,1,0,0
674,0,0,0,1,7,235,37,29,1,1,1
675,0,0,1,0,9,225,41,28,1,2,2
676,0,0,0,1,9,235,32,25,1,0,0
677,1,0,0,0,9,118,37,28,0,0,0
678,0,0,0,1,9,235,43,38,0,1,0
679,1,0,0,0,10,179,30,19,1,0,0
680,0,0,0,1,10,291,40,25,0,1,1
681,1,0,0,0,10,225,41,28,1,2,2
682,0,0,1,0,11,300,43,25,0,2,1
683,0,0,0,1,11,225,41,28,1,2,2
684,0,0,0,1,11,179,30,19,1,0,0
685,0,0,0,1,5,118,50,31,0,1,0
686,1,0,0,0,5,118,50,31,0,1,0
687,0,0,0,1,5,118,37,28,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0
689,0,0,0,1,5,179,30,19,1,0,0
690,0,0,0,0,5,378,36,21,0,2,4
691,0,1,0,0,5,179,40,22,1,2,0
692,1,0,0,0,5,155,34,25,0,2,0
693,1,0,0,0,5,235,32,25,1,0,0
694,0,0,0,1,5,291,40,25,0,1,1
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [18]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Standardizing the data

In [19]:
from sklearn.preprocessing import StandardScaler


absenteeism_scaler = StandardScaler()

In [20]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

#Creating a Customer scaler for our data
class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [21]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [22]:
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [23]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [24]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [25]:
absenteeism_scaler.fit(unscaled_inputs)

/home/purvi/.local/lib/python3.6/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [26]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [27]:
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.030796,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.030796,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.929019,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.030796,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,-0.268611,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.030796,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.030796,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.030796,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,0,0,0,1,-0.568019,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1,0,0,0,1.527833,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,-1.166834,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.929019,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.330204,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.330204,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.330204,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,0,0,0,1,-0.867426,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,0,0,0,1,1.527833,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.330204,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.330204,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.867426,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.867426,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.867426,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.867426,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,0.030796,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,0,0,1,0,0.629611,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,0,0,0,1,0.629611,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,0.629611,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,0.629611,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,0.929019,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,0.929019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,0.929019,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,0,0,1,0,1.228426,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,0,0,0,1,1.228426,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,0,0,0,1,1.228426,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.568019,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.568019,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.568019,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.568019,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.568019,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.568019,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.568019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.568019,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.568019,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.568019,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.568019,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.568019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [28]:
scaled_inputs.shape

(700, 11)

### Splitting the data into train & test

In [29]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, test_size = 0.2, random_state = 20)

In [33]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)

In [34]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)

### Logistic regression with sklearn

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [36]:
reg = LogisticRegression()

In [37]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
reg.score(x_train,y_train)

0.7767857142857143

### Model Evaluation

In [39]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [40]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [42]:
np.sum((model_outputs==y_train))

435

In [43]:
model_outputs.shape[0]

560

In [45]:
Accuracy = np.sum((model_outputs==y_train)) / model_outputs.shape[0]
Accuracy

0.7767857142857143

### intercept and coefficients

In [46]:
reg.intercept_

array([-1.60957471])

In [47]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [48]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [49]:
feature_name = unscaled_inputs.columns.values

In [51]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

              Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                    Pets    -0.273374

In [52]:
summary_table.index = summary_table.index + 1

summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

summary_table = summary_table.sort_index()
summary_table

              Feature name  Coefficient
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                    Pets    -0.273374

## Testing lr model

In [54]:
reg.score(x_test,y_test)

0.7357142857142858

In [55]:
predicted_proba = reg.predict_proba(x_test)

predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.61140118, 0.38859882],
       [0.28761821, 0.71238179],
       [0.30178515, 0.69821485],
       [0.50492844, 0.49507156],
       [0.75768232, 0.24231768],
       [0.40227404, 0.59772596],
       [0.73957814, 0.26042186],
       [0.21977314, 0.78022686],
       [0.5601409 , 0.4398591 ],
       [0.39358874, 0.60641126],
       [0.75811152, 0.24188848],
       [0.50286997, 0.49713003],
       [0.74137615, 0.25862385],
       [0.59310285, 0.40689715],
       [0.19240806, 0.80759194],
       [0.40110655, 0.59889345],
       [0.28055298, 0.71944702],
       [0.75682238, 0.24317762],
       [0.75323874, 0.24676126],
       [0.7585402 , 0.2414598 ],
       [0.49819184, 0.50180816],
       [0.70700732, 0.29299268],
       [0.3052464 , 0.6947536 ],
       [0.75540613, 0.24459387],
       [0.17966732, 0.82033268],
       [0.60806156, 0.39193844],
       [0.09400654, 0.90599346],
       [0.73557043, 0.26442957],
       [0.67849766, 0.32150234],
       [0.6779872 , 0.3220128 ],
       [0.29497024, 0.70502976],
       [0.30376028, 0.69623972],
       [0.73420328, 0.26579672],
       [0.22415673, 0.77584327],
       [0.75458879, 0.24541121],
       [0.75509628, 0.24490372],
       [0.92448842, 0.07551158],
       [0.73912737, 0.26087263],
       [0.23823076, 0.76176924],
       [0.70359899, 0.29640101],
       [0.74227211, 0.25772789],
       [0.68460407, 0.31539593],
       [0.11591943, 0.88408057],
       [0.5612932 , 0.4387068 ],
       [0.40452581, 0.59547419],
       [0.75768232, 0.24231768],
       [0.23962732, 0.76037268],
       [0.24968437, 0.75031563],
       [0.2996782 , 0.7003218 ],
       [0.36495955, 0.63504045],
       [0.7409274 , 0.2590726 ],
       [0.92558608, 0.07441392],
       [0.73145547, 0.26854453],
       [0.28379938, 0.71620062],
       [0.53265409, 0.46734591],
       [0.87778217, 0.12221783],
       [0.30326582, 0.69673418],
       [0.47760936, 0.52239064],
       [0.77739845, 0.22260155],
       [0.28761821, 0.71238179],
       [0.80291504, 0.19708496],
       [0.86732465, 0.13267535],
       [0.75379629, 0.24620371],
       [0.75423014, 0.24576986],
       [0.75596036, 0.24403964],
       [0.12930173, 0.87069827],
       [0.75379629, 0.24620371],
       [0.27679152, 0.72320848],
       [0.75497368, 0.24502632],
       [0.80068474, 0.19931526],
       [0.40339941, 0.59660059],
       [0.28761821, 0.71238179],
       [0.30213847, 0.69786153],
       [0.29254388, 0.70745612],
       [0.56071713, 0.43928287],
       [0.56474607, 0.43525393],
       [0.75466347, 0.24533653],
       [0.12930173, 0.87069827],
       [0.23738775, 0.76261225],
       [0.86759359, 0.13240641],
       [0.92590765, 0.07409235],
       [0.08788486, 0.91211514],
       [0.35675261, 0.64324739],
       [0.6130671 , 0.3869329 ],
       [0.40396248, 0.59603752],
       [0.39582409, 0.60417591],
       [0.21937231, 0.78062769],
       [0.15389863, 0.84610137],
       [0.43937218, 0.56062782],
       [0.7386761 , 0.2613239 ],
       [0.75552858, 0.24447142],
       [0.8760147 , 0.1239853 ],
       [0.19538249, 0.80461751],
       [0.50462418, 0.49537582],
       [0.75596036, 0.24403964],
       [0.70457368, 0.29542632],
       [0.75811152, 0.24188848],
       [0.8667854 , 0.1332146 ],
       [0.30277181, 0.69722819],
       [0.73822433, 0.26177567],
       [0.3930306 , 0.6069694 ],
       [0.75811152, 0.24188848],
       [0.75682238, 0.24317762],
       [0.70115414, 0.29884586],
       [0.73374656, 0.26625344],
       [0.40847604, 0.59152396],
       [0.50492844, 0.49507156],
       [0.70311094, 0.29688906],
       [0.75497368, 0.24502632],
       [0.55956451, 0.44043549]])

In [56]:
predicted_proba.shape

(140, 2)

In [57]:
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547419,
       0.24231768, 0.76037268, 0.75031563, 0.7003218 , 0.63504045,
       0.2590726 , 0.07441392, 0.26854453, 0.71620062, 0.46734591,
       0.12221783, 0.69673418, 0.52239064, 0.22260155, 0.71238179,
       0.19708496, 0.13267535, 0.24620371, 0.24576986, 0.24403964,
       0.87069827, 0.24620371, 0.72320848, 0.24502632, 0.19931526,
       0.59660059, 0.71238179, 0.69786153, 0.70745612, 0.43928287,
       0.43525393, 0.24533653, 0.87069827, 0.76261225, 0.13240641,
       0.07409235, 0.91211514, 0.64324739, 0.3869329 , 0.59603752,
       0.60417591, 0.78062769, 0.84610137, 0.56062782, 0.2613239 ,
       0.24447142, 0.1239853 , 0.80461751, 0.49537582, 0.24403964,
       0.29542632, 0.24188848, 0.1332146 , 0.69722819, 0.26177567,
       0.6069694 , 0.24188848, 0.24317762, 0.29884586, 0.26625344,
       0.59152396, 0.49507156, 0.29688906, 0.24502632, 0.44043549])

## Saving model

In [58]:
import pickle

In [59]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [60]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)